# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - if [ `uname` = "Linux" ]; then sudo apt-get install patchelf; fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("BuildExecutable"); Pkg.test("BuildExecutable"; coverage=true)'
